#!/bin/sh

if [ "$(id -u)" = "0" ]; then
    MITMKEYS_DIR=/etc/mitmkeys
else
    MITMKEYS_DIR=~/.mitmkeys
fi

mkdir -p "$MITMKEYS_DIR"
chmod 0700 "$MITMKEYS_DIR"

### SSH
echo "=> Generating SSH keypair with empty passphrase in $MITMKEYS_DIR"
rm -f "$MITMKEYS_DIR/id_rsa"
ssh-keygen -t rsa -N '' -f "$MITMKEYS_DIR/id_rsa"


### SSL
echo "=> Generating self-signed SSL certificate with empty passphrase in $MITMKEYS_DIR"
# Generate the Private Key
openssl genrsa -des3 -passout pass:0000 -out "$MITMKEYS_DIR/server.key" 1024

# Generate a Certificate Signing Request
openssl req -new -key "$MITMKEYS_DIR/server.key" -passin pass:0000 -batch -out "$MITMKEYS_DIR/server.csr"

# Remove Passphrase from Key
cp "$MITMKEYS_DIR/server.key" "$MITMKEYS_DIR/server.key.orig"
openssl rsa -passin pass:0000 -in "$MITMKEYS_DIR/server.key.orig" -out "$MITMKEYS_DIR/server.key"
rm "$MITMKEYS_DIR/server.key.orig"

# Generate a Self-Signed Certificate
openssl x509 -req -days 365 -in "$MITMKEYS_DIR/server.csr" -signkey "$MITMKEYS_DIR/server.key" -out "$MITMKEYS_DIR/server.crt"

echo "=> Done."
